[project]
name = "elysia-ai-kernel"
version = "1.3.0"
description = "AI Core for ElysiaAI"
authors = [{name = "Elysia20220909"}]
dependencies = [
    "fastapi",
    "uvicorn",
    "httpx",
    "langchain",
    "langchain-community",
    "ollama",
    "pydantic-settings",
    "pymilvus[model]",
    "pytest",
    "ruff",
    "python-dotenv",
    "pydantic"
]

[tool.setuptools]
packages = ["kernel"]
