[project]
name = "elysia-ai-kernel"
version = "0.1.0"
description = "AI Core for ElysiaAI"
dependencies = [
    "fastapi",
    "uvicorn",
    "httpx",
    "langchain",
    "langchain-community",
    "ollama",
    "pydantic-settings",
    "pymilvus[model]",
    "pytest",
    "python-dotenv",
    "pydantic"
]

[tool.setuptools]
packages = ["kernel"]
