# Elysia AI - Google Cloud Build Configuration
# Automated CI/CD Pipeline

steps:
  # Step 1: Build Docker Image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/elysia-ai:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/elysia-ai:latest"
      - "-f"
      - "Dockerfile.production"
      - "."
    id: "build-image"

  # Step 2: Push to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/elysia-ai:$COMMIT_SHA"
    id: "push-image"

  # Step 3: Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/elysia-ai:latest"
    id: "push-latest"

  # Step 4: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "elysia-ai"
      - "--image"
      - "gcr.io/$PROJECT_ID/elysia-ai:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "10"
      - "--port"
      - "3000"
      - "--set-env-vars"
      - "NODE_ENV=production,PORT=3000,PYTHON_PORT=8000"
    id: "deploy-cloud-run"

# Container Registry
images:
  - "gcr.io/$PROJECT_ID/elysia-ai:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/elysia-ai:latest"

# Build timeout
timeout: "1200s"

# Build options
options:
  machineType: "N1_HIGHCPU_8"
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
