#!/usr/bin/env bash
set -Eeuo pipefail

umask 077

TARGET_DIR="${TARGET_DIR:-/opt/elisia-core}"
INSTALL_DOCKER="auto"
START_STACK="true"
PULL_IMAGES="true"
VALIDATE_ONLY="false"
BIND_IP_OVERRIDE=""
TIMEZONE_OVERRIDE=""
DOMAIN_SUFFIX=""
GRAFANA_PASSWORD_OVERRIDE=""
BASIC_AUTH_PASSWORD_OVERRIDE=""
MQTT_USER_OVERRIDE=""
MQTT_PASSWORD_OVERRIDE=""
OLLAMA_MODEL=""

usage() {
  cat <<'EOF'
Stark Home Local Server Build auto setup

Usage:
  ./setup.sh [options]

Options:
  --target-dir DIR              Deployment directory. Default: /opt/elisia-core
  --bind-ip IP                  LAN IP to bind exposed services. Example: 10.10.20.30
  --timezone TZ                 Time zone. Default comes from .env.example
  --domain-suffix NAME          Rebuild service domains under this suffix. Example: home.arpa
  --grafana-password PASS       Set Grafana admin password
  --basic-auth-password PASS    Set Caddy basic auth password for Prometheus
  --mqtt-user USER              MQTT username. Default: homeassistant
  --mqtt-password PASS          MQTT password
  --pull-model MODEL            Pull an Ollama model after startup. Example: llama3.2
  --install-docker              Install Docker Engine if missing
  --skip-docker-install         Do not install Docker Engine
  --no-pull                     Skip docker compose pull
  --no-start                    Prepare and validate, but do not start containers
  --validate-only               Only validate current files and .env
  -h, --help                    Show this help

Examples:
  sudo ./setup.sh --install-docker --bind-ip 10.10.20.30 --pull-model llama3.2
  ./setup.sh --no-start --bind-ip 10.10.20.30
EOF
}

log() {
  printf '\n==> %s\n' "$*"
}

warn() {
  printf 'WARN: %s\n' "$*" >&2
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

as_root() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    command -v sudo >/dev/null 2>&1 || die "sudo is required for this step. Re-run as root or install sudo."
    sudo "$@"
  fi
}

docker_cmd() {
  if docker info >/dev/null 2>&1; then
    docker "$@"
  else
    as_root docker "$@"
  fi
}

compose_cmd() {
  docker_cmd compose -f "${TARGET_DIR}/compose.yaml" "$@"
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is required but was not found."
}

random_hex() {
  openssl rand -hex 32
}

random_b64() {
  openssl rand -base64 32 | tr -d '\n'
}

read_env_value() {
  local key="$1"
  local file="$2"
  local value
  local first
  local last

  if [[ ! -f "${file}" ]]; then
    return 0
  fi

  value="$(grep -E "^${key}=" "${file}" | tail -n 1 | cut -d= -f2- || true)"

  first="${value:0:1}"
  last="${value: -1}"

  if [[ "${first}" == "'" && "${last}" == "'" ]]; then
    value="${value:1:${#value}-2}"
  elif [[ "${first}" == '"' && "${last}" == '"' ]]; then
    value="${value:1:${#value}-2}"
  fi

  printf '%s' "${value}"
}

is_placeholder() {
  local value="${1:-}"
  [[ -z "${value}" || "${value}" == replace-with-* ]]
}

set_env_value() {
  local key="$1"
  local value="$2"
  local file="$3"
  local rendered
  local escaped

  rendered="$(render_env_value "${value}")"
  escaped="$(printf '%s' "${rendered}" | sed 's/[&|\\]/\\&/g')"

  if grep -q -E "^${key}=" "${file}"; then
    sed -i "s|^${key}=.*|${key}=${escaped}|" "${file}"
  else
    printf '%s=%s\n' "${key}" "${rendered}" >>"${file}"
  fi
}

render_env_value() {
  local value="$1"

  if [[ "${value}" == *'$'* || "${value}" == *' '* || "${value}" == *'#'* ]]; then
    if [[ "${value}" == *"'"* ]]; then
      die "Cannot safely write an .env value containing a single quote. Use a generated password or remove the quote."
    fi

    printf "'%s'" "${value}"
    return
  fi

  printf '%s' "${value}"
}

record_secret() {
  local label="$1"
  local value="$2"
  local file="${TARGET_DIR}/setup-secrets.txt"

  if [[ ! -f "${file}" ]]; then
    {
      printf '# Generated by deploy/elisia-core/setup.sh\n'
      printf '# Store these in a password manager, then delete this file from the VM.\n'
      printf '# Do not commit this file.\n\n'
    } >"${file}"
    chmod 600 "${file}"
  fi

  printf '%s=%s\n' "${label}" "${value}" >>"${file}"
}

install_docker_engine() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    log "Docker Engine and Compose plugin already available"
    return
  fi

  [[ -f /etc/os-release ]] || die "Cannot detect OS. Docker auto-install supports Debian/Ubuntu only."
  # shellcheck disable=SC1091
  . /etc/os-release

  case "${ID}" in
    ubuntu|debian) ;;
    *) die "Docker auto-install supports Debian/Ubuntu only. Detected: ${ID}" ;;
  esac

  local codename="${VERSION_CODENAME:-}"
  [[ -n "${codename}" ]] || die "VERSION_CODENAME is missing in /etc/os-release."

  log "Installing Docker Engine for ${ID} ${codename}"
  as_root apt-get update
  as_root apt-get install -y ca-certificates curl gnupg openssl rsync
  as_root install -m 0755 -d /etc/apt/keyrings

  curl -fsSL "https://download.docker.com/linux/${ID}/gpg" | as_root tee /etc/apt/keyrings/docker.asc >/dev/null
  as_root chmod a+r /etc/apt/keyrings/docker.asc

  local arch
  arch="$(dpkg --print-architecture)"
  printf 'deb [arch=%s signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/%s %s stable\n' \
    "${arch}" "${ID}" "${codename}" | as_root tee /etc/apt/sources.list.d/docker.list >/dev/null

  as_root apt-get update
  as_root apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  as_root systemctl enable --now docker >/dev/null 2>&1 || warn "Could not enable docker with systemctl; continuing"

  if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    as_root usermod -aG docker "${SUDO_USER}" || warn "Could not add ${SUDO_USER} to docker group"
    warn "User ${SUDO_USER} may need to log out and back in for docker group membership."
  fi
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --target-dir)
        TARGET_DIR="$2"
        shift 2
        ;;
      --bind-ip)
        BIND_IP_OVERRIDE="$2"
        shift 2
        ;;
      --timezone)
        TIMEZONE_OVERRIDE="$2"
        shift 2
        ;;
      --domain-suffix)
        DOMAIN_SUFFIX="$2"
        shift 2
        ;;
      --grafana-password)
        GRAFANA_PASSWORD_OVERRIDE="$2"
        shift 2
        ;;
      --basic-auth-password)
        BASIC_AUTH_PASSWORD_OVERRIDE="$2"
        shift 2
        ;;
      --mqtt-user)
        MQTT_USER_OVERRIDE="$2"
        shift 2
        ;;
      --mqtt-password)
        MQTT_PASSWORD_OVERRIDE="$2"
        shift 2
        ;;
      --pull-model)
        OLLAMA_MODEL="$2"
        shift 2
        ;;
      --install-docker)
        INSTALL_DOCKER="yes"
        shift
        ;;
      --skip-docker-install)
        INSTALL_DOCKER="no"
        shift
        ;;
      --no-pull)
        PULL_IMAGES="false"
        shift
        ;;
      --no-start)
        START_STACK="false"
        shift
        ;;
      --validate-only)
        VALIDATE_ONLY="true"
        START_STACK="false"
        PULL_IMAGES="false"
        INSTALL_DOCKER="no"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "Unknown option: $1"
        ;;
    esac
  done
}

prepare_directory() {
  local current_user="${SUDO_USER:-${USER:-root}}"

  if [[ ! -d "${TARGET_DIR}" ]]; then
    log "Creating ${TARGET_DIR}"
    as_root mkdir -p "${TARGET_DIR}"
    as_root chown "${current_user}:${current_user}" "${TARGET_DIR}" 2>/dev/null || true
  fi

  [[ -f "${TARGET_DIR}/compose.yaml" ]] || die "compose.yaml not found in ${TARGET_DIR}. Copy deploy/elisia-core there first."
  [[ -f "${TARGET_DIR}/.env.example" ]] || die ".env.example not found in ${TARGET_DIR}."

  if [[ "${VALIDATE_ONLY}" == "true" ]]; then
    return
  fi

  mkdir -p \
    "${TARGET_DIR}/backups" \
    "${TARGET_DIR}/caddy" \
    "${TARGET_DIR}/homepage/config" \
    "${TARGET_DIR}/homepage/icons" \
    "${TARGET_DIR}/prometheus" \
    "${TARGET_DIR}/grafana/provisioning/datasources" \
    "${TARGET_DIR}/mosquitto/config" \
    "${TARGET_DIR}/mosquitto/data" \
    "${TARGET_DIR}/mosquitto/log"

  if [[ -f "${TARGET_DIR}/backup-volumes.sh" ]]; then
    chmod +x "${TARGET_DIR}/backup-volumes.sh"
  fi
}

ensure_env() {
  local env_file="${TARGET_DIR}/.env"

  if [[ ! -f "${env_file}" ]]; then
    log "Creating .env from .env.example"
    cp "${TARGET_DIR}/.env.example" "${env_file}"
    chmod 600 "${env_file}"
  else
    chmod 600 "${env_file}"
  fi

  if [[ -n "${BIND_IP_OVERRIDE}" ]]; then
    set_env_value "BIND_IP" "${BIND_IP_OVERRIDE}" "${env_file}"
  fi

  if [[ -n "${TIMEZONE_OVERRIDE}" ]]; then
    set_env_value "TZ" "${TIMEZONE_OVERRIDE}" "${env_file}"
  fi

  if [[ -n "${DOMAIN_SUFFIX}" ]]; then
    set_env_value "DOMAIN_AI" "ai.${DOMAIN_SUFFIX}" "${env_file}"
    set_env_value "DOMAIN_HA" "ha.${DOMAIN_SUFFIX}" "${env_file}"
    set_env_value "DOMAIN_STATUS" "status.${DOMAIN_SUFFIX}" "${env_file}"
    set_env_value "DOMAIN_DASH" "dash.${DOMAIN_SUFFIX}" "${env_file}"
    set_env_value "DOMAIN_GIT" "git.${DOMAIN_SUFFIX}" "${env_file}"
    set_env_value "DOMAIN_N8N" "n8n.${DOMAIN_SUFFIX}" "${env_file}"
    set_env_value "DOMAIN_GRAFANA" "grafana.${DOMAIN_SUFFIX}" "${env_file}"
    set_env_value "DOMAIN_PROMETHEUS" "prometheus.${DOMAIN_SUFFIX}" "${env_file}"
  fi

  ensure_secret_value "WEBUI_SECRET_KEY" "hex" "${env_file}"
  ensure_secret_value "GITEA_DB_PASSWORD" "b64" "${env_file}"
  ensure_secret_value "N8N_DB_PASSWORD" "b64" "${env_file}"
  ensure_secret_value "N8N_ENCRYPTION_KEY" "b64" "${env_file}"

  if [[ -n "${GRAFANA_PASSWORD_OVERRIDE}" ]]; then
    set_env_value "GRAFANA_ADMIN_PASSWORD" "${GRAFANA_PASSWORD_OVERRIDE}" "${env_file}"
  else
    local grafana_password
    grafana_password="$(read_env_value "GRAFANA_ADMIN_PASSWORD" "${env_file}")"
    if is_placeholder "${grafana_password}"; then
      grafana_password="$(random_b64)"
      set_env_value "GRAFANA_ADMIN_PASSWORD" "${grafana_password}" "${env_file}"
      record_secret "GRAFANA_ADMIN_PASSWORD" "${grafana_password}"
    fi
  fi

  ensure_basic_auth_hash "${env_file}"
  ensure_mqtt_env "${env_file}"
}

ensure_secret_value() {
  local key="$1"
  local mode="$2"
  local env_file="$3"
  local current
  local generated

  current="$(read_env_value "${key}" "${env_file}")"
  if ! is_placeholder "${current}"; then
    return
  fi

  if [[ "${mode}" == "hex" ]]; then
    generated="$(random_hex)"
  else
    generated="$(random_b64)"
  fi

  set_env_value "${key}" "${generated}" "${env_file}"
}

ensure_basic_auth_hash() {
  local env_file="$1"
  local current
  local password
  local hash
  local caddy_image

  current="$(read_env_value "BASIC_AUTH_HASH" "${env_file}")"
  if [[ -z "${BASIC_AUTH_PASSWORD_OVERRIDE}" ]] && ! is_placeholder "${current}"; then
    return
  fi

  password="${BASIC_AUTH_PASSWORD_OVERRIDE:-$(random_b64)}"
  caddy_image="$(read_env_value "CADDY_IMAGE" "${env_file}")"
  caddy_image="${caddy_image:-caddy:2}"

  log "Generating Caddy basic auth hash"
  hash="$(docker_cmd run --rm "${caddy_image}" caddy hash-password --plaintext "${password}" | tr -d '\r')"
  [[ -n "${hash}" ]] || die "Failed to generate Caddy basic auth hash."

  set_env_value "BASIC_AUTH_HASH" "${hash}" "${env_file}"

  if [[ -z "${BASIC_AUTH_PASSWORD_OVERRIDE}" ]]; then
    record_secret "BASIC_AUTH_PASSWORD" "${password}"
  fi
}

ensure_mqtt_env() {
  local env_file="$1"
  local username
  local password

  username="${MQTT_USER_OVERRIDE:-$(read_env_value "MQTT_USERNAME" "${env_file}")}"
  username="${username:-homeassistant}"
  set_env_value "MQTT_USERNAME" "${username}" "${env_file}"

  if [[ -n "${MQTT_PASSWORD_OVERRIDE}" ]]; then
    password="${MQTT_PASSWORD_OVERRIDE}"
  else
    password="$(read_env_value "MQTT_PASSWORD" "${env_file}")"
    if is_placeholder "${password}"; then
      password="$(random_b64)"
      record_secret "MQTT_PASSWORD" "${password}"
    fi
  fi

  set_env_value "MQTT_PASSWORD" "${password}" "${env_file}"
}

create_mqtt_password_file() {
  local env_file="${TARGET_DIR}/.env"
  local password_file="${TARGET_DIR}/mosquitto/config/passwords"
  local username
  local password
  local mosquitto_image

  if [[ -f "${password_file}" && -z "${MQTT_PASSWORD_OVERRIDE}" ]]; then
    log "Keeping existing Mosquitto password file"
    return
  fi

  username="$(read_env_value "MQTT_USERNAME" "${env_file}")"
  password="$(read_env_value "MQTT_PASSWORD" "${env_file}")"
  mosquitto_image="$(read_env_value "MOSQUITTO_IMAGE" "${env_file}")"
  mosquitto_image="${mosquitto_image:-eclipse-mosquitto:2}"

  [[ -n "${username}" ]] || die "MQTT_USERNAME is empty."
  [[ -n "${password}" ]] || die "MQTT_PASSWORD is empty."

  log "Creating Mosquitto password file"
  docker_cmd run --rm \
    -v "${TARGET_DIR}/mosquitto/config:/mosquitto/config" \
    "${mosquitto_image}" \
    mosquitto_passwd -b -c /mosquitto/config/passwords "${username}" "${password}"
  chmod 600 "${password_file}"
}

validate_stack() {
  log "Validating Docker Compose syntax"
  compose_cmd config --quiet
}

start_stack() {
  if [[ "${PULL_IMAGES}" == "true" ]]; then
    log "Pulling container images"
    compose_cmd pull
  fi

  log "Starting E.L.I.S.I.A. Core stack"
  compose_cmd up -d
  compose_cmd ps
}

pull_ollama_model() {
  [[ -n "${OLLAMA_MODEL}" ]] || return
  [[ "${START_STACK}" == "true" ]] || {
    warn "--pull-model was set, but --no-start/--validate-only prevents model pull."
    return
  }

  log "Pulling Ollama model: ${OLLAMA_MODEL}"
  compose_cmd exec -T ollama ollama pull "${OLLAMA_MODEL}"
}

main() {
  parse_args "$@"

  prepare_directory

  if [[ "${INSTALL_DOCKER}" == "yes" ]]; then
    install_docker_engine
  elif [[ "${INSTALL_DOCKER}" == "auto" ]] && { ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; }; then
    install_docker_engine
  fi

  require_command docker

  if [[ "${VALIDATE_ONLY}" == "true" ]]; then
    validate_stack
    log "Validation complete"
    exit 0
  fi

  require_command openssl
  require_command sed
  require_command grep
  require_command cut

  ensure_env
  create_mqtt_password_file
  validate_stack

  if [[ "${START_STACK}" == "true" ]]; then
    start_stack
    pull_ollama_model
  else
    log "Prepared without starting containers"
  fi

  if [[ -f "${TARGET_DIR}/setup-secrets.txt" ]]; then
    warn "Generated plaintext bootstrap secrets are in ${TARGET_DIR}/setup-secrets.txt."
    warn "Move them to a password manager, then delete that file."
  fi

  log "Done"
}

main "$@"
